### ISSUE TITLE
Node.js Mac OS X 10.5 PPC binaries

### ISSUE THREAD

**Issue by niutech** [ibmruntimes/node#14]
Could you please provide binaries of node.js for Mac OS X 10.5 PPC or at least provide a guide on how to easily build it? I have a PowerBook G4 and Xcode 3.14. Thanks!

**Comment by mangeshPSL** [comment]
@andrewlow  hi I have some doubt regarding nodejs in ppc

**Comment by andrewlow** [comment]
@mangeshPSL could you provide more detail on your doubts?

**Comment by mangeshPSL** [comment]
@andrewlow  I am trying nodejs version v0.10.40 on ppc64le could you please tell me some links actually I am working on atom.io to be ported on ppc64le but it requires nodejs v0.10.40 and I have v0.10.25 . which atom.io internally tries to updated through following link
http://nodejs.org/dist/v0.10.40/node-v0.10.40-linux-ppc64.tar.gz
so could you help me out with some usefull stuff .

**Comment by andrewlow** [comment]
Well, you probably want to look here https://developer.ibm.com/node/sdk/#v11 -- it appears the most current version there is 0.10.41

**Comment by mangeshPSL** [comment]
thanks for the stuff but @andrewlow its Sdk kit , however I want to work on command base i.e through putty(SSH) . is there any binary for nodejs version v0.10.40

**Comment by joransiu** [comment]
It's been 3 years since this issue been discussed, and I suspect a requirement to support Mac OS X on PPC is probably becoming less and less relevant.   Gonna close this item.

**Comment by barracuda156** [comment]
Any solution to build nodejs for PowerPC G5?

**Comment by andrewlow** [comment]
Probably no. The root cause here is that there are many variations of the PPC chips out there - and one area where the variations differ is their FPU implementation. Consider the previously linked issue: https://github.com/ibmruntimes/v8ppc/issues/97 - while this may not be specific to the G5 - a similar problem will happen.

Unless we find someone who has the right motivation, time and skills to address these differences in the code base - it's not going to happen.

If you go looking around - it is possible to build/run the V8 code in 'simulation' mode - which effectively emulates the CPU - this is slow - but does work.
